language: cpp

compiler:
    - gcc
    - clang

before_install:
    - git clone https://github.com/fundamental/rtosc
    - cd rtosc && mkdir build && cd build && cmake ..
    - make && sudo make install && cd ../..
    - sudo apt-get install libjack-dev libslang2-dev

script:
    - autoreconf --install && ./configure && make
